[package]
name = "esp-temperature-sensor"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "esp-temperature-sensor"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []
indoor_sensor = []
outdoor_sensor = []

[dependencies]
esp-idf-svc = "0.52"
serde_json = "1.0.140"
anyhow = "1.0.98"
dotenvy_macro = "0.15.7"
embedded-svc = "0.29.0"
aht20-driver = { version = "2.0.0", default-features = false }
bmp280-driver = "0.0.7"

[build-dependencies]
embuild = "0.33"
